# Generated by Django 4.0.4 on 2022-05-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options_alter_productcategory_options_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartModel',
        ),
    ]
